### ISSUE TITLE
To get Embeddings for research papers and reviews

### ISSUE THREAD

**Issue by aritzzz** [allenai/specter#4]
Can we also get the representation for review text through the model? Is yes, then could you guide on how? Also, the sample metadata file in the readme has the title and abstract information, but in the ./data it also has other keys like cited by, etc. Plus, where should I specify the path to the actual paper text data?

**Comment by armancohan** [comment]
Are you referring to paper reviews? If so you should be able to embed them by putting the text of the review in the `abstract` field in the metadata file and if the review has a title, add it in the `title` field (otherwise add the paper's title). 
SPECTER was not trained on full-text, but if you want to use full-text you can put it in the `abstract` field in the metadata file (note though that currently long text will be truncated to 512 tokens).

**Comment by sergeyf** [comment]
Closing this issue. Feel free to reopen if you have any further questions @aritzzz
